version: "3.9"
services:
  db:
    image: "postgres"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "docker"
      POSTGRES_HOSTNAME: "localhost"
    volumes:
      - data:/var/lib/postgresql/data
  
  server:
    build: .
    ports:
      - "5000:5000"
    links: 
      - db:postgres
volumes:
  data:
